# Generated by Django 5.2.15 on 2026-06-16 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0002_product_product_man_categor_2c7112_idx_and_more"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product"], name="reviews_rev_product_a9ee0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user"], name="reviews_rev_user_id_a65d48_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "is_approved"], name="reviews_rev_product_99e47c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["-created_at"], name="reviews_rev_created_03e07d_idx"
            ),
        ),
    ]
