# Generated by Django 5.2.15 on 2026-06-16 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0002_product_product_man_categor_2c7112_idx_and_more"),
        ("search_and_recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["user"], name="search_and__user_id_b1889e_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "-score"], name="search_and__user_id_62152d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(fields=["user"], name="search_and__user_id_1c3bb8_idx"),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["-timestamp"], name="search_and__timesta_cedb64_idx"
            ),
        ),
    ]
