# Generated by Django 5.2.15 on 2026-06-16 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="product_man_categor_2c7112_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["seller"], name="product_man_seller__229a00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active"], name="product_man_is_acti_f37d25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured"], name="product_man_is_feat_fe36c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="product_man_categor_bdb16c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="product_man_price_2fc42b_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="product_man_created_5961b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product"], name="product_man_product_46501d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productspecification",
            index=models.Index(
                fields=["product"], name="product_man_product_e1c786_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product"], name="product_man_product_198af0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seller",
            index=models.Index(
                fields=["is_verified"], name="product_man_is_veri_229b37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seller",
            index=models.Index(
                fields=["-rating"], name="product_man_rating_1df405_idx"
            ),
        ),
    ]
