# Generated by Django 5.2.15 on 2026-06-16 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0002_product_product_man_categor_2c7112_idx_and_more"),
        ("wishlist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoritestore",
            unique_together={("user", "seller")},
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "product")},
        ),
        migrations.AddIndex(
            model_name="favoritestore",
            index=models.Index(fields=["user"], name="wishlist_fa_user_id_406ce5_idx"),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(fields=["user"], name="wishlist_wi_user_id_ec8321_idx"),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(
                fields=["user", "product"], name="wishlist_wi_user_id_2f12fb_idx"
            ),
        ),
    ]
