# Generated by Django 4.2.7 on 2026-06-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart_and_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
